# Generated by Django 5.0 on 2024-01-09 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_package_customization_orderpackage_packageitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='product',
        ),
        migrations.AddField(
            model_name='customization',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.orderitem'),
        ),
    ]
